# Generated by Django 3.1.12 on 2025-12-31 11:40

from django.db import migrations, models
import process.models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processsubmission',
            name='ai_file',
            field=models.FileField(blank=True, null=True, upload_to=process.models.ProcessSubmission.process_submission_path),
        ),
        migrations.AlterField(
            model_name='processsubmission',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to=process.models.ProcessSubmission.process_submission_path),
        ),
        migrations.AlterField(
            model_name='processsubmission',
            name='grammarly_report',
            field=models.FileField(blank=True, null=True, upload_to=process.models.ProcessSubmission.process_submission_path),
        ),
        migrations.AlterField(
            model_name='processsubmission',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to=process.models.ProcessSubmission.process_submission_path),
        ),
        migrations.AlterField(
            model_name='processsubmission',
            name='plag_file',
            field=models.FileField(blank=True, null=True, upload_to=process.models.ProcessSubmission.process_submission_path),
        ),
    ]
