# Generated by Django 3.1.12 on 2025-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20251126_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('unallocated', 'Unallocated'), ('completed', 'Completed'), ('hold', 'Hold'), ('query', 'Query'), ('cancelled', 'Cancelled'), ('Review', 'Review')], default='draft', max_length=20),
        ),
    ]
