# Generated by Django 3.1.12 on 2025-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20251129_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_creation_method',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_summary', 'AI Summary Generated')], default='ai_summary', help_text='Whether job was created manually or via AI summary workflow', max_length=20),
        ),
    ]
