# Generated by Django 3.1.12 on 2025-12-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0009_remove_masking_and_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='final_copy_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='final_copy_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='structure_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='structure_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='writer_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WriterSubmission',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('structure', 'Structure'), ('final_copy', 'Final Copy')], max_length=20)),
                ('notes', models.TextField(help_text='Structure: 250 words, Final Copy: 3000 words')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_submissions', to='marketing.job')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writer_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='submission_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketing.writersubmission')),
            ],
            options={
                'db_table': 'submission_files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='writersubmission',
            index=models.Index(fields=['job'], name='writer_subm_job_id_d8a268_idx'),
        ),
        migrations.AddIndex(
            model_name='writersubmission',
            index=models.Index(fields=['submitted_by'], name='writer_subm_submitt_7b8274_idx'),
        ),
        migrations.AddIndex(
            model_name='writersubmission',
            index=models.Index(fields=['submission_type'], name='writer_subm_submiss_eede2c_idx'),
        ),
    ]
