# Generated by Django 3.1.12 on 2025-12-04 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0010_auto_20251203_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writersubmission',
            unique_together={('job', 'submission_type', 'submitted_by')},
        ),
    ]
