# Generated by Django 3.1.12 on 2025-12-04 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0011_auto_20251204_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allocated_to_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_jobs_allocated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='allocated_to_process_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
