# Generated by Django 3.1.12 on 2025-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0009_auto_20251203_1732'),
        ('accounts', '0010_auto_20251121_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialisations',
            field=models.ManyToManyField(blank=True, related_name='users', to='superadminpanel.SpecialisationMaster'),
        ),
    ]
