# Generated by Django 3.1.12 on 2025-12-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0014_organisationmaster'),
        ('accounts', '0011_customuser_specialisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='superadminpanel.organisationmaster'),
        ),
    ]
