# Generated by Django 3.1.12 on 2025-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20251224_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
