# Generated by Django 3.1.12 on 2025-12-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='child_organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
