# Generated by Django 3.1.12 on 2025-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0005_taskallocation_priority_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskallocation',
            options={'ordering': ['job', 'task_type', 'allocated_at']},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Allocation'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('process', 'Process'), ('review', 'Review'), ('active', 'Active'), ('open', 'Open'), ('close', 'Close'), ('hold', 'On Hold'), ('query', 'Query'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='taskallocation',
            unique_together=set(),
        ),
    ]
