# Generated by Django 3.1.12 on 2025-12-01 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0009_remove_masking_and_template'),
        ('allocator', '0007_job_status_close_from_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reassigned', 'Reassigned')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'allocation_action_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobAllocation',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('allocation_type', models.CharField(choices=[('writer', 'Writer'), ('process', 'Process Team')], default='writer', max_length=20)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_allocations', to=settings.AUTH_USER_MODEL)),
                ('marketing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='marketing.job')),
            ],
            options={
                'db_table': 'job_allocations',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='allocationhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='allocationhistory',
            name='new_user',
        ),
        migrations.RemoveField(
            model_name='allocationhistory',
            name='previous_user',
        ),
        migrations.RemoveField(
            model_name='allocationhistory',
            name='task_allocation',
        ),
        migrations.DeleteModel(
            name='CountryBankingResource',
        ),
        migrations.RemoveField(
            model_name='job',
            name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobquery',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobquery',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='jobquery',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='jobquery',
            name='task_allocation',
        ),
        migrations.RemoveField(
            model_name='processteamprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='allocated_to',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='writerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AllocationHistory',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobQuery',
        ),
        migrations.DeleteModel(
            name='ProcessTeamProfile',
        ),
        migrations.DeleteModel(
            name='TaskAllocation',
        ),
        migrations.DeleteModel(
            name='WriterProfile',
        ),
        migrations.AddField(
            model_name='allocationactionlog',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='allocator.joballocation'),
        ),
        migrations.AddField(
            model_name='allocationactionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['marketing_job'], name='job_allocat_marketi_7c0c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['allocated_to'], name='job_allocat_allocat_229741_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['status'], name='job_allocat_status_748cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['allocation_type'], name='job_allocat_allocat_153449_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationactionlog',
            index=models.Index(fields=['allocation'], name='allocation__allocat_83aecc_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationactionlog',
            index=models.Index(fields=['timestamp'], name='allocation__timesta_2bcf5d_idx'),
        ),
    ]
