# Generated by Django 3.1.12 on 2025-12-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0008_auto_20251201_1840'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allocationactionlog',
            name='allocation__allocat_83aecc_idx',
        ),
        migrations.RemoveIndex(
            model_name='allocationactionlog',
            name='allocation__timesta_2bcf5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='joballocation',
            name='job_allocat_marketi_7c0c0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='joballocation',
            name='job_allocat_allocat_229741_idx',
        ),
        migrations.RemoveIndex(
            model_name='joballocation',
            name='job_allocat_status_748cfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='joballocation',
            name='job_allocat_allocat_153449_idx',
        ),
    ]
