# Generated by Django 3.1.12 on 2025-12-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0009_auto_20251201_1842'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allocationactionlog',
            index=models.Index(fields=['allocation'], name='allocation__allocat_83aecc_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationactionlog',
            index=models.Index(fields=['timestamp'], name='allocation__timesta_2bcf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['marketing_job'], name='job_allocat_marketi_7c0c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['allocated_to'], name='job_allocat_allocat_229741_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['status'], name='job_allocat_status_748cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='joballocation',
            index=models.Index(fields=['allocation_type'], name='job_allocat_allocat_153449_idx'),
        ),
    ]
