# Generated by Django 3.1.12 on 2025-12-03 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0010_auto_20251203_1528'),
        ('superadminpanel', '0008_specialisationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('edited', 'Edited'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('changes_history', models.JSONField(blank=True, default=dict, help_text='Track changes made by SuperAdmin')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_drops_edited', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_drop', to='marketing.job')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drops_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Drop',
                'verbose_name_plural': 'Job Drops',
                'db_table': 'job_drops',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
