# Generated by Django 3.1.12 on 2025-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0009_auto_20251203_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='google_calendar_event_id',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='google_calendar_sync_failed_at',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='google_calendar_sync_started_at',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='google_calendar_synced_at',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='is_synced_to_calendar',
        ),
    ]
