# Generated by Django 3.1.12 on 2025-12-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0010_auto_20251218_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='project_group',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatemaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='templatemaster',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='templatemaster',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='JobTask',
        ),
        migrations.DeleteModel(
            name='JobTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateMaster',
        ),
    ]
