# Generated by Django 3.1.12 on 2025-12-24 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0011_auto_20251219_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organisations', to='superadminpanel.organisationmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation Master',
                'verbose_name_plural': 'Organisation Masters',
                'db_table': 'organisation_master',
                'ordering': ['-created_at'],
            },
        ),
    ]
