# Generated by Django 3.1.12 on 2025-12-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0012_organisationmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationMaster',
        ),
    ]
