# Generated by Django 3.1.12 on 2025-12-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0014_organisationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('appointment', 'Appointment Letter'), ('experience', 'Experience Letter'), ('joining', 'Joining Letter'), ('no_objection', 'No Objection Letter'), ('offer', 'Offer Letter'), ('payment', 'Payment Letter'), ('relieving', 'Relieving Letter'), ('salary_increment', 'Salary Increment Letter'), ('termination', 'Termination Letter'), ('warning', 'Warning Letter')], max_length=50, unique=True)),
                ('template_content', models.TextField(help_text='HTML template content')),
                ('is_trigger', models.BooleanField(default=False, help_text='Triggers specific system actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_templates_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_templates_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Template',
                'verbose_name_plural': 'Letter Templates',
                'db_table': 'letter_templates',
                'ordering': ['letter_type'],
            },
        ),
    ]
