# Generated by Django 3.1.12 on 2025-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0015_lettertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='letter_type',
            field=models.CharField(choices=[('appointment', 'Appointment Letter'), ('experience', 'Experience Letter'), ('joining', 'Joining Letter'), ('no_objection', 'No Objection Letter'), ('offer', 'Offer Letter'), ('payment', 'Payment Letter'), ('relieving', 'Relieving Letter'), ('salary_increment', 'Salary Increment Letter'), ('termination', 'Termination Letter'), ('warning', 'Warning Letter')], max_length=50),
        ),
    ]
