# Generated by Django 3.1.12 on 2025-12-26 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0016_auto_20251226_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettertemplate',
            options={'verbose_name': 'Letter Template', 'verbose_name_plural': 'Letter Templates'},
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_id', models.CharField(max_length=50, unique=True)),
                ('letter_type', models.CharField(max_length=50)),
                ('rendered_content', models.TextField(help_text='Final rendered HTML content')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_deleted', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_generated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_letters', to='superadminpanel.lettertemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Letter',
                'verbose_name_plural': 'Generated Letters',
                'db_table': 'generated_letters',
                'ordering': ['-generated_at'],
            },
        ),
    ]
