# Generated by Django 3.1.12 on 2025-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0017_auto_20251226_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='field_data',
            field=models.TextField(blank=True, help_text='JSON of form field values', null=True),
        ),
    ]
